# Generated by Django 3.1.7 on 2021-03-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=500)),
                ('vehicle_number', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='employee_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('work_location', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('attendance', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='parking_slot_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('slot_type', models.CharField(max_length=500)),
                ('price', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='rented_parking_slot_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.CharField(max_length=500)),
                ('customer_name', models.CharField(max_length=500)),
                ('customer_number', models.CharField(max_length=500)),
                ('customer_location', models.CharField(max_length=500)),
                ('total_slots_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sign_in_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='slot_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField()),
                ('location_name', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('slot_number_selected', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='slot_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='temp_customer_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=500)),
                ('vehicle_number', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='temp_slot_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField()),
                ('location_name', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('slot_number_selected', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
