# Generated by Django 3.1.7 on 2021-03-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_slot_details',
            name='slot_name',
            field=models.SlugField(max_length=500),
        ),
    ]
