# Generated by Django 3.1.7 on 2021-03-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210320_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_slot_details',
            name='price',
            field=models.IntegerField(),
        ),
    ]
