# Generated by Django 3.1.7 on 2021-03-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210320_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('vehicle_number', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
