# Generated by Django 3.1.7 on 2021-03-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_reg_vehicle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg_vehicle',
            new_name='save_customer',
        ),
    ]
