# Generated by Django 3.1.7 on 2021-03-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210326_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='save_customer',
        ),
    ]
