# Generated by Django 3.1.7 on 2021-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_save_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='price',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_details',
            name='slot_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_customer_details',
            name='price',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_customer_details',
            name='slot_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
