# Generated by Django 3.1.7 on 2021-03-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='not_box',
            new_name='messages',
        ),
    ]
