# Generated by Django 3.1.7 on 2021-03-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210331_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='messages',
            new_name='b',
        ),
    ]
