# Generated by Django 3.1.7 on 2021-03-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20210331_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='c',
            field=models.CharField(default='', max_length=20000),
            preserve_default=False,
        ),
    ]
