# Generated by Django 3.1.7 on 2021-03-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_notification_c'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
