# Generated by Django 3.1.7 on 2021-03-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_box', models.CharField(max_length=20000)),
                ('user_name', models.CharField(max_length=20000)),
            ],
        ),
    ]
