# Generated by Django 3.1.7 on 2021-03-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notification',
            new_name='notification_user',
        ),
    ]
