# Generated by Django 3.1.7 on 2021-03-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20210331_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_user',
            name='slot_id',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
